[build]
  base = "docs"
  publish = "build"
  command = "bun run build"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_OMIT_KEYS = "ALGOLIA_APP_ID,ALGOLIA_API_KEY"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
