name: Examples

on:
  push:
    branches: [ "develop" ]
#   pull_request:
    # branches: [ "main" ]
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  examples:
    name: Build & Run Examples
    # Only run if build passed or was triggered directly
    if: ${{ github.event.workflow_run == null || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      examples_status: ${{ job.status }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
        
      - name: Cache apt packages
        uses: actions/cache@v4
        with:
          path: /var/cache/apt/archives
          key: ${{ runner.os }}-apt-examples-${{ hashFiles('**/meson.build') }}
          restore-keys: |
            ${{ runner.os }}-apt-examples-
            
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build libpcre2-dev
          python -m pip install --upgrade pip
          pip install 'meson>=1.0.0'

      - name: Configure with examples
        run: meson setup .build-examples -Dtests=false -Dexamples=true
        
      - name: Build examples
        run: meson compile -C .build-examples
        
      - name: Run example tests
        run: |
          cd .build-examples/examples
          # Test help output of examples
          for example in *; do
            if [ -x "$example" ] && [[ "$example" != *.* ]]; then
              echo "Testing $example --help"
              ./$example --help || exit 1
              echo "------------------------------"
            fi
          done
          
      # Archive examples as artifacts
      - name: Upload examples
        uses: actions/upload-artifact@v4
        with:
          name: examples
          path: .build-examples/examples/
          retention-days: 7